### ISSUE TITLE
MIC Key Generation at DCP Creation Level

### ISSUE THREAD

**Issue by jpviollet** [SMPTE/st429-2#13]
While we understand that moving forward KDMs are expected to deliver the MIC Key (instead of having the SM derive the MIC Key for the Content key), we are concerned about the consequences of delivering a KDM-borne MIC Key that was not created (at DCP creation level) using the legacy MIC Key algorithm.

In fact, if MXF Track Files are not “created” using the legacy MIC algorithm, all DCPs will appear corrupted regarding MIC Item verification by the large number of deployed servers that do NOT support (and may never support) KDM-borne MIC Key.

This is a concern, and to avoid this, we believe that DCP should still be created using a MIC Key generated using the legacy MIC algorithm – and then provided to Media Blocks through the KDM. This does NOT contradict the DCI requirement that forbids SM to derive the MIC Key from the Content key for new implementations (and as such, new SM implementations don’t have to implement the RNG algorithm now forbidden by DCI specification.)

To avoid confusion, we are only asking the DCP creation tools (NOT the playback tools) to keep generating MIC Keys in compliance with this legacy algorithm, and by doing so, all legacy deployed playback tools will still properly identify MIC Item corruption appropriately. Otherwise, it won’t be possible anymore to know if a MIC Item verification failure is a true failure, or just due to a device that can’t process KDM-Borne MIC Key.

As a note, a secondary side effect would also be a slight increase of logged information for these legacy playback devices (through the addition of a FrameMICError exception token to the FrameSequencePlayed entry in which the error occurred.) This is not expected to create a log capacity issue on our implementations – just pointing this out here, just in case, as we can’t speak for other implementations.

During March 2nd 2023 27C Documents Maintenance meeting, it appeared more appropriate to include such proposed MIC Key creation requirement in ST 492-2 rather than in ST 429-6 to avoid confusion with playback equipment expectations (because ST 429-6 contains “decryption processing model”), explaining the creation of this ST 429-2 Github issue.

As such, the following constraint is proposed to be added to ST 429-2:

“**ST 429-6 deprecates the usage of the legacy MIC Key algorithm [ insert legacy algo reference here ] for Security Managers. However, the MIC Key needed at the time of DCP generation to create any MIC Item present in Encrypted Track Files shall still be obtained using this legacy algorithm [ insert legacy algorithm reference here ] to avoid issue with legacy equipment that are not able to process KDM-Borne MIC Key**."

Note: To be in-sync with this proposed addition, ST 429-6 may also need to be modified along the following lines (I created a new ST 429-6 GitHub Case for this - see https://github.com/SMPTE/st429-6/issues/5):

In Annex B, change:
“_This method is no longer considered cryptographically adequate and should not be used. Furthermore, [FIPS PUB 186-2](https://doc.smpte-doc.org/st429-6-private/main/#bib-fips-186-2) has been withdrawn and the method is therefore reproduced below to allow the interpretation of legacy Track Files that used it_.”

To:
“**_This method is should not be used by Security Managers (SMs)._**"

In section 9.1, change:
“_Annex B specifies a deprecated method by which the MIC Key is derived from the Cipher Key_. “

To:
“**_Annex B specifies a deprecated method by which the Security Managers (SMs) derived the MIC Key from the Cipher Key._**”

**Comment by dcbullock** [comment]
I added a section to 429-2 constraining KDM MDMK type keys and a Note that includes most of @jpviollet text in the issue description.

**Comment by twechsel** [comment]
JPV is correct in that the legacy MIC algorithm needs to be used going forward.  While FIPS has oversight to goings-on within the cryptographic module (MB), it does not in the DCP/KDM creation processes.  Attached is a document providing background to the RNG issue, and DCI's proposal for how the industry can migrate to KDM-borne MIC key delivery.  It appears the in-process SMPTE standards amendments are aligned to support this.

[RNG KDM-Borne MIC Key Summary Description.docx](https://github.com/SMPTE/st429-2/files/10927678/RNG.KDM-Borne.MIC.Key.Summary.Description.docx)
