### ISSUE TITLE
Erroneous reference to EntryPoint element

### ISSUE THREAD

**Issue by jhursty** [SMPTE/st429-2#2]
The text in Chapter 9.9:

"When present, a MainMarkers asset shall not contain any marker with an Offset value, minus the EntryPoint of the enclosing MainMarkers element, that exceeds the duration of the Reel."

This text refers to `EntryPoint`, but `EntryPoint` is not present in a `MainMarkers` asset per ST 429-7.

At this point the constraint might better be stated as:

"When present, a MainMarkers asset shall have a value of `IntrinsicDuration` that is equal to or less than the duration of the respective Reel."

**Comment by palemieux** [comment]
> This text refers to EntryPoint, but EntryPoint is not present in a MainMarkers asset per ST 429-7.

The MarkerAssetType has an EntryPoint:

![image](https://user-images.githubusercontent.com/4871350/213667241-5699354f-46ba-4a66-816b-704a82ddf727.png)

**Comment by jhursty** [comment]
Per Fig. 11, the MarkerAssetType does not reference an external resource. From ST 429-7, 8.1.5 EntryPoint [optional]:

"This element shall only be present when the Asset refers to an external resource such as a Track File."

Also, RDD-52 now says in 8.2 Reel Duration: "The value of all Duration elements as defined in SMPTE ST 429-7 in a reel shall be equal, including for Timed Text and Aux Data tracks, if present."

I amend my proposed resolution to be "When present, a MainMarkers asset shall have a value of IntrinsicDuration that is equal to the duration of the respective Reel."

**Comment by palemieux** [comment]
Unfortunately, ST 429-7 also states: _The Offset of each Marker (see 8.3.1.3) is the position from the start of the timeline and the Intrinsic Duration of the timeline shall correspond to the Offset of the last Marker._

So IntrinsicDuration cannot always be equal to the duration of the parent Reel.

What is done in the field today?

**Comment by jhursty** [comment]
> What is done in the field today?

All of our clients (and our implementation) are aligned with RDD-52, i.e., "The value of all Duration elements ...  shall be equal".

I think that "correspond," in the sense "have a close similarity; match or agree almost exactly," allows for some interpretation about the value of Intrinsic Duration in a MainMarkers Asset within the narrow scope of ST 429-7 itself. Perhaps it is this ambiguity that has led to the practice documented in RDD-52.

Setting that aside, my issue is with the use of EntryPoint in the original quoted text. In the interest of addressing that issue without becoming responsible for the Intrinsic Duration discussion, I offer this third edition of my proposed resolution:

"When present, a MainMarkers asset shall not contain any marker with an Offset value that exceeds the duration of the respective Reel."

**Comment by SteveLLamb** [comment]
> I think that "correspond," in the sense "have a close similarity; match or agree almost exactly," allows for some interpretation about the value of Intrinsic Duration in a MainMarkers Asset within the narrow scope of ST 429-7 itself. Perhaps it is this ambiguity that has led to the practice documented in RDD-52.

Yes, this is the issue that led to RDD-52 having that text of "being equal" for Duration. This is current practice due to implementation expectations in the field. 

> "This element shall only be present when the Asset refers to an external resource such as a Track File."

> Also, RDD-52 now says in 8.2 Reel Duration: "The value of all Duration elements as defined in SMPTE ST 429-7 in a reel shall be equal, including for Timed Text and Aux Data tracks, if present."

Currently EntryPoint and Duration are not included due that that reference in 429-7 to only being used for external tracks, and Markers are not considered a track in this context. IntrinsicDuration is therefore equal to the last offset +1 (offset started from frame 1 - "0" offset). 

I think this all needs to be specifically addressed in 429-7. Which Dean and I started to document in https://github.com/SMPTE/st429-7/issues/6

> Setting that aside, my issue is with the use of EntryPoint in the original quoted text. In the interest of addressing that issue without becoming responsible for the Intrinsic Duration discussion, I offer this third edition of my proposed resolution:

> "When present, a MainMarkers asset shall not contain any marker with an Offset value that exceeds the duration of the respective Reel."

I'm fine with this text, perhaps with a slight tweak: "When present, a MainMarkers asset shall not contain any marker with an Offset value or contain an IntrinsicDuration value that exceeds the duration of the respective Reel."

The other issues John and I have with EntryPoint and Duration can be dealt with in 429-7.

**Comment by palemieux** [comment]
@SteveLLamb see https://github.com/SMPTE/st429-2-private/pull/2
