### ISSUE TITLE
Inconsistent caps - d-cinema/D-cinema/D-Cinema

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/st429-2#8]
All instance should be `D-Cinema`, and link back to definition.

**Comment by palemieux** [comment]
The term D-Cinema is now capitalize per https://github.com/SMPTE/st429-2-private/commit/b247d8b8a1ed5324ba886cb5608a9f82adcce632

I think we need to think more about how to handle terms and acronyms, especially one like D-Cinema that is used across many documents.
